# Generated by Django 2.0.4 on 2018-04-30 18:23

import employee_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0002_auto_20180428_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=50, unique=True,
                                   validators=[employee_manager.models.validate_email]),
        ),
    ]
